package ch.ge.ve.protopoc.service.model;

import java.math.BigInteger;
import java.util.List;
import java.util.Objects;

/**
 * Model class for a decryption proof such as those generated by algorithm 5.50
 */
public class DecryptionProof {
    private final List<BigInteger> t;
    private final BigInteger s;

    public DecryptionProof(List<BigInteger> t, BigInteger s) {
        this.t = t;
        this.s = s;
    }

    public List<BigInteger> getT() {
        return t;
    }

    public BigInteger getS() {
        return s;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        DecryptionProof that = (DecryptionProof) o;
        return Objects.equals(t, that.t) &&
                Objects.equals(s, that.s);
    }

    @Override
    public int hashCode() {
        return Objects.hash(t, s);
    }
}
