INSERT INTO ACCOUNT (ID, USERNAME, PASSWORD) VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi');
INSERT INTO ACCOUNT (ID, USERNAME, PASSWORD) VALUES (2, 'user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC');

INSERT INTO AUTHORITIES (ID, NAME) VALUES (1, "ROLE_USER");
INSERT INTO AUTHORITIES (ID, NAME) VALUES (2, "ROLE_ADMIN");

INSERT INTO ACCOUNT_AUTHORITIES (ACCOUNT_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO ACCOUNT_AUTHORITIES (ACCOUNT_ID, AUTHORITY_ID) VALUES (1, 2);
INSERT INTO ACCOUNT_AUTHORITIES (ACCOUNT_ID, AUTHORITY_ID) VALUES (2, 1);
