@startuml
actor "Election Officer / \nSimulation" as eo
actor "Authority [1-s]" as auth
actor "Bulletin Board" as bb

eo -> auth : startPartialDecryption
auth -> bb : getShuffleAndProofs
auth -> bb : publishPartialDecryptionsAndProofs
auth --> eo : done

@enduml