@startuml
!include style.puml
participant "Election Officer / \nSimulation" as eo
participant "Authority [1-s]" as auth
participant "Bulletin Board" as bb

activate eo
eo -> bb : publishPublicParameters

== Key generation ==
loop for each authority
    eo -> auth : generateKeys
    activate auth
    auth -> bb : getPublicParameters
    bb --> auth : public parameters
    auth -> bb : publishPublicKeyPart
    auth --> eo : done
    deactivate auth
end

loop for each authority
    eo -> auth : buildPublicKey
    activate auth
    auth -> bb : getPublicKeyParts
    bb --> auth : public key parts
    auth -> auth : buildPublicKey
    auth --> eo : done
    deactivate auth
end

== Election configuration ==

eo -> bb : publishElectionSet

== Credentials generation ==
loop for each authority
    eo -> auth : generateElectorateData
    activate auth
    auth -> bb : getElectionSet
    bb --> auth : election set
    auth -> bb : publishPublicCredentials
    auth --> eo : done
    deactivate auth
end

loop for each authority
    eo -> auth : buildPublicCredentials
    activate auth
    auth -> bb : getPublicCredentialsParts
    bb --> auth : public credential parts
    auth -> auth : combine public credentials
    auth --> eo : done
    deactivate auth
    deactivate eo
end
@enduml