@startuml
!include style.puml
hide footbox
participant "Election Officer / \nSimulation" as eo
participant "Bulletin Board" as bb

activate eo
eo -> bb : getTallyData
activate bb
bb --> eo : partial decryptions and proofs
deactivate bb

eo -> eo : check decryption proofs

eo -> bb : publishTally
deactivate eo

@enduml